### ISSUE TITLE
Embedded PDFs sometimes appear empty in auditing mode

### ISSUE THREAD

**Issue by nateflowers** [johnnyflowers/schoolcalendars#65]
http://www.schoolcalendars.org/california/santa-ana-unified-school-district-915481/calendar-25762/audit/

Calendars at the top listed as "Calendar" are not displaying a calendar image for me. The others that are marked with a year are displaying fine. If it's working fine for you, it might be a caching issue for me.

**Comment by johnnyflowers** [comment]
I've seen this problem as well. Caching does seem like the culprit. Will investigate.

**Comment by johnnyflowers** [comment]
I've found a couple of things that can cause this. First, some calendar urls are just no good, and embedding them just results in spinning while waiting for a server response. And second, there are some urls that resolve as a file download (octet-stream file type) rather than a browser-viewable PDF (pdf file type).

I've added a link to the original PDF/download above the embed. If a calendar is pulling up blank, check the link and see if it's one of the above two cases.

**Comment by nateflowers** [comment]
Will do.

**Comment by johnnyflowers** [comment]
Just tacked on a little more explanation to the comment above!

**Comment by nateflowers** [comment]
Got it. I'll deactivate if the calendar URL is no good, or let it go if
legit.
